name = "rachacuca-backend"
main = "worker.js"
compatibility_date = "2024-01-01"

[[durable_objects.bindings]]
name = "RoomDO"
class_name = "RoomDO"
script_name = "rachacuca-backend"

[[durable_objects.bindings]]
name = "RecordesDO"
class_name = "RecordesDO"
script_name = "rachacuca-backend"

[[durable_objects.bindings]]
name = "HistoricoDO"
class_name = "HistoricoDO"
script_name = "rachacuca-backend"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDO"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["RecordesDO"]

[[migrations]]
tag = "v3"
new_sqlite_classes = ["HistoricoDO"]